D 2023-01-30 11:25:59,348| DEBUG    | [factory.py:factory:<module>:19] - Not in REPL -> leaving logger event level as is.
I 2023-01-30 11:25:59,964| INFO     | [get_data.py:get_data:read_special_list_excel:137] - 成功获取登录login所有用例，共12条用例
I 2023-01-30 11:25:59,965| INFO     | [get_data.py:get_data:read_special_list_excel:138] - [['测试成功登录', '/apitest/login/', 'post', 'data', "{'username':'test01','password':'123456'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1000, 'Usercheck ok', '登录验证成功'], ['测试用户名为空', '/apitest/login/', 'post', 'data', "{'username':'','password':'123456'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1001, 'Username is null', '用户名不能为空'], ['测试密码为空', '/apitest/login/', 'post', 'data', "{'username':'test02','password':''}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1002, 'Password is null', '密码不能为空'], ['测试用户名和密码均为空', '/apitest/login/', 'post', 'data', "{'username':'','password':''}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1001, 'Username is null', '用户名不能为空'], ['测试用户名错误', '/apitest/login/', 'post', 'data', "{'username':'test03','password':'123456'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1003, 'Username error', '用户名错误'], ['测试密码错误', '/apitest/login/', 'post', 'data', "{'username':'test03','password':'123'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1003, 'Password error', '密码错误'], ['测试用户名和密码均错误', '/apitest/login/', 'post', 'data', "{'username':'test05','password':'123'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1003, 'Username error', '用户名错误'], ['测试用户名为中文', '/apitest/login/', 'post', 'data', "{'username':'你好','password':'123456'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1003, 'Username error', '用户名错误'], ['测试用户名为数字', '/apitest/login/', 'post', 'data', "{'username':'123456','password':'123456'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1003, 'Username error', '用户名错误'], ['测试密码为无效最大边界值', '/apitest/login/', 'post', 'data', "{'username':'test05','password':'12345678945647898468464'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1003, 'Username error', '用户名错误'], ['测试用户名为特殊字符', '/apitest/login/', 'post', 'data', "{'username':'*%$','password':'123456'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1003, 'Username error', '用户名错误'], ['测试密码长度超过限制', '/apitest/login/', 'post', 'data', "{'username':'test15','password':'123456784948494848484486486486'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1004, 'Password error', '用户名错误']]
I 2023-01-30 11:25:59,980| INFO     | [get_data.py:get_data:read_special_rows_list_excel:160] - 成功从获取第12到12用例,共1条用例
I 2023-01-30 11:25:59,980| INFO     | [get_data.py:get_data:read_special_rows_list_excel:161] - [['测试密码长度超过限制', '/apitest/login/', 'post', '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 1004, 'Password error', '用户名错误']]
I 2023-01-30 11:25:59,997| INFO     | [get_data.py:get_data:read_special_rows_list_excel:160] - 成功从获取第1到4用例,共4条用例
I 2023-01-30 11:25:59,998| INFO     | [get_data.py:get_data:read_special_rows_list_excel:161] - [['验证用户名密码正确登陆成功', '/integration/login', 'post', 'json', '{\n "data": {\n "password": "12345678",\n "userName": "root"\n }\n}', '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 0, '登录成功', 1], ['验证用户名错误登陆失败', '/integration/login', 'post', 'json', '{\n "data": {\n "password": "12345678",\n "userName": "oot"\n }\n}', '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 501, '用户名或口令错误', 1], ['验证密码错误登陆失败', '/integration/login', 'post', 'json', '{\n "data": {\n "password": "1234578",\n "userName": "root"\n }\n}', '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 501, '用户名或口令错误', 1], ['验证用户名密码都错误登陆失败', '/integration/login', 'post', 'json', '{\n "data": {\n "password": "1234678",\n "userName": "rot"\n }\n}', '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', 501, '用户名或口令错误', 1]]
I 2023-01-30 11:26:00,015| INFO     | [get_data.py:get_data:read_special_list_excel:137] - 成功获取注册signup所有用例，共11条用例
I 2023-01-30 11:26:00,016| INFO     | [get_data.py:get_data:read_special_list_excel:138] - [['signup_01', '测试成功注册', '/apitest/signup/', 'post', 'json', "{'username':'test06','password':'123456','confirm':'123456','name':'成功注册用户'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', "{'Status':1000,'Result':'Success','Message':'注册成功'}", 'users, info', "select count(*),(select count(*) from info where name='成功注册用户') from users where username='test06' and password=md5('123456')", '(1,1)'], ['signup_02', '测试用户名为空', '/apitest/signup/', 'post', 'json', "{'username':'','password':'123456','confirm':'123456','name':'注册用户名为空用户'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', "{'Status':1001,'Result':'Username is null','Message':'注册失败，用户名不能为空'}", 'users, info', "select count(*),(select count(*) from info where name='注册用户名为空用户') from users where username='' and password=md5('123456')", '(0,0)'], ['signup_03', '测试密码为空', '/apitest/signup/', 'post', 'json', "{'username':'test07','password':'','confirm':'123456','name':'注册密码为空用户'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', "{'Status':1002,'Result':'Password is null','Message':'注册失败，密码不能为空'}", 'users, info', "select count(*),(select count(*) from info where name='注册密码为空用户') from users where username='test07' and password=md5('')", '(0,0)'], ['signup_04', '测试确认密码为空', '/apitest/signup/', 'post', 'json', "{'username':'test08','password':'123456','confirm':'','name':'注册确认密码为空用户'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', "{'Status':1003,'Result':'Confirm password is null','Message':'注册失败，确认密码不能为空'}", 'users, info', "select count(*),(select count(*) from info where name='注册确认密码为空用户') from users where username='test08' and password=md5('123456')", '(1,1)'], ['signup_05', '测试姓名为空', '/apitest/signup/', 'post', 'json', "{'username':'test09','password':'123456','confirm':'123456','name':''}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', "{'Status':1004,'Result':'Name is null','Message':'注册失败，姓名不能为空'}", 'users, info', "select count(*),(select count(*) from info where name='') from users where username='test09' and password=md5('123456')", '(0,0)'], ['signup_06', '测试参数全为空', '/apitest/signup/', 'post', 'json', "{'username':'','password':'','confirm':'','name':''}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', "{'Status':1001,'Result':'Username is null','Message':'注册失败，用户名不能为空'}", 'users, info', "select count(*),(select count(*) from info where name='') from users where username='' and password=md5('')", '(0,0)'], ['signup_07', '测试两个密码不一致', '/apitest/signup/', 'post', 'json', "{'username':'test10','password':'123456','confirm':'123','name':'注册两个密码不一致用户'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', "{'Status':1009,'Result':'Confirm password error','Message':'注册失败，两个密码不一致'}", 'users, info', "select count(*),(select count(*) from info where name='注册两个密码不一致用户') from users where username='test10' and password=md5('123456')", '(0,0)'], ['signup_08', '测试用户重复注册', '/apitest/signup/', 'post', 'json', "{'username':'test11','password':'123456','confirm':'123456','name':'重复注册用户'}", '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', "{'Status':1010,'Result':'Username test11 is taken','Message':'注册失败，用户名已被占用'}", 'users, info', "select count(*),(select count(*) from info where name='重复注册用户') from users where username='test11' and password=md5('123456')", '(1,1)'], ['signup_09', '测试用户名为中文', '/apitest/signup/', 'post', 'json', '{"username":"阳靖康","password":"123456","confirm":"123456","name":"中文注册用户"}', '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', '{"Status":1000,"Result":"Success","Message":"注册成功"}', 'users, info', "select count(*),(select count(*) from info where name='中文注册用户') from users where username='阳靖康' and password=md5('123456')", '(1,1)'], ['signup_10', '测试用户名为特殊字符', '/apitest/signup/', 'post', 'json', '{"username":"%￥#@&*","password":"123456","confirm":"123456","name":"特殊字符用户"}', '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', '{"Status":1000,"Result":"Success","Message":"注册成功"}', 'users, info', "select count(*),(select count(*) from info where name='特殊字符用户') from users where username='%￥#@&*' and password=md5('123456')", '(1,1)'], ['signup_10', '测试用户名为特殊字符', '/apitest/signup/', 'post', 'json', '{"username":"test12","password":"阳靖康","confirm":"阳靖康","name":"注册密码为中文"}', '1、正确输入接口地址 2、正确输入请求参数 3、查看响应body是否正确', '{"Status":1000,"Result":"Success","Message":"注册成功"}', 'users, info', "select count(*),(select count(*) from info where name='注册密码为中文') from users where username='阳靖康'", '(1,1)']]
D 2023-01-30 11:26:00,020| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.address`.
D 2023-01-30 11:26:00,022| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.address` has been localized to `en_US`.
D 2023-01-30 11:26:00,024| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.automotive`.
D 2023-01-30 11:26:00,025| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.automotive` has been localized to `en_US`.
D 2023-01-30 11:26:00,026| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.bank`.
D 2023-01-30 11:26:00,027| DEBUG    | [factory.py:factory:_find_provider_class:105] - Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
D 2023-01-30 11:26:00,027| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.barcode`.
D 2023-01-30 11:26:00,028| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.barcode` has been localized to `en_US`.
D 2023-01-30 11:26:00,029| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.color`.
D 2023-01-30 11:26:00,030| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.color` has been localized to `en_US`.
D 2023-01-30 11:26:00,031| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.company`.
D 2023-01-30 11:26:00,032| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.company` has been localized to `en_US`.
D 2023-01-30 11:26:00,033| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.credit_card`.
D 2023-01-30 11:26:00,033| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.credit_card` has been localized to `en_US`.
D 2023-01-30 11:26:00,034| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.currency`.
D 2023-01-30 11:26:00,034| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.currency` has been localized to `en_US`.
D 2023-01-30 11:26:00,035| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.date_time`.
D 2023-01-30 11:26:00,036| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.date_time` has been localized to `en_US`.
D 2023-01-30 11:26:00,037| DEBUG    | [factory.py:factory:_find_provider_class:125] - Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
D 2023-01-30 11:26:00,037| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.geo`.
D 2023-01-30 11:26:00,038| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.geo` has been localized to `en_US`.
D 2023-01-30 11:26:00,038| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.internet`.
D 2023-01-30 11:26:00,040| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.internet` has been localized to `en_US`.
D 2023-01-30 11:26:00,040| DEBUG    | [factory.py:factory:_find_provider_class:125] - Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
D 2023-01-30 11:26:00,041| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.job`.
D 2023-01-30 11:26:00,042| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.job` has been localized to `en_US`.
D 2023-01-30 11:26:00,042| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.lorem`.
D 2023-01-30 11:26:00,043| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.lorem` has been localized to `en_US`.
D 2023-01-30 11:26:00,045| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.misc`.
D 2023-01-30 11:26:00,045| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.misc` has been localized to `en_US`.
D 2023-01-30 11:26:00,046| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.person`.
D 2023-01-30 11:26:00,048| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.person` has been localized to `en_US`.
D 2023-01-30 11:26:00,052| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.phone_number`.
D 2023-01-30 11:26:00,054| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.phone_number` has been localized to `en_US`.
D 2023-01-30 11:26:00,070| DEBUG    | [factory.py:factory:_find_provider_class:125] - Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
D 2023-01-30 11:26:00,071| DEBUG    | [factory.py:factory:_find_provider_class:125] - Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
D 2023-01-30 11:26:00,071| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.ssn`.
D 2023-01-30 11:26:00,073| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.ssn` has been localized to `en_US`.
D 2023-01-30 11:26:00,074| DEBUG    | [factory.py:factory:_find_provider_class:125] - Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
D 2023-01-30 11:26:00,089| DEBUG    | [connectionpool.py:connectionpool:_new_conn:971] - Starting new HTTPS connection (1): p10496-hk-bbs.ejoy.com:443
D 2023-01-30 11:26:00,863| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - https://p10496-hk-bbs.ejoy.com:443 "GET /api/bbs/S3G%E4%BA%8C%E5%91%A8%E5%B9%B4%E4%B8%A4%E8%A1%8C%E6%83%85%E4%B9%A6/index?count=100 HTTP/1.1" 200 None
D 2023-01-30 11:26:00,865| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'https://p10496-hk-bbs.ejoy.com/api/bbs/S3G二周年两行情书/index?count=100', 'method': 'get'}
D 2023-01-30 11:26:00,867| DEBUG    | [asserts.py:asserts:assert_code:30] - Response_Code实际结果为：6088b66e2230325e4b1970e5120a11fc
D 2023-01-30 11:26:00,867| DEBUG    | [asserts.py:asserts:assert_code:31] - Response_Code预期结果为：3e4547b4bb12e9047950252d64b63472
E 2023-01-30 11:26:00,867| ERROR    | [asserts.py:asserts:assert_code:35] - 断言失败，Response_Code实际结果为：6088b66e2230325e4b1970e5120a11fc，Response预期结果为：3e4547b4bb12e9047950252d64b63472
E 2023-01-30 11:26:00,867| ERROR    | [asserts.py:asserts:assert_code:36] - 断言用例不通过！
D 2023-01-30 11:26:00,918| DEBUG    | [conf.py:conf:conf_get_db:30] - 读数据库服务器配置文件/Users/yangjingkang/PycharmProjects/YJK_api-master/confs/db.conf成功，数据库信息是{'host': '172.16.9.128', 'db': 'wa_test', 'user': 'root', 'passwd': '123456'}
E 2023-01-30 11:26:10,922| ERROR    | [mysql.py:mysql:connect:30] - 数据库连接失败，连接参数为{'host': '172.16.9.128', 'db': 'wa_test', 'user': 'root', 'passwd': '123456'}
E 2023-01-30 11:26:10,922| ERROR    | [mysql.py:mysql:connect:31] - 错误原因(2003, "Can't connect to MySQL server on '172.16.9.128' (timed out)")
D 2023-01-30 11:26:11,665| DEBUG    | [conf.py:conf:conf_get_db:30] - 读数据库服务器配置文件/Users/yangjingkang/PycharmProjects/YJK_api-master/confs/db.conf成功，数据库信息是{'host': '172.16.9.128', 'db': 'wa_test', 'user': 'root', 'passwd': '123456'}
E 2023-01-30 11:26:21,667| ERROR    | [mysql.py:mysql:connect:30] - 数据库连接失败，连接参数为{'host': '172.16.9.128', 'db': 'wa_test', 'user': 'root', 'passwd': '123456'}
E 2023-01-30 11:26:21,667| ERROR    | [mysql.py:mysql:connect:31] - 错误原因(2003, "Can't connect to MySQL server on '172.16.9.128' (timed out)")
D 2023-01-30 11:27:36,665| DEBUG    | [factory.py:factory:<module>:19] - Not in REPL -> leaving logger event level as is.
D 2023-01-30 11:27:37,020| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.address`.
D 2023-01-30 11:27:37,022| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.address` has been localized to `en_US`.
D 2023-01-30 11:27:37,024| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.automotive`.
D 2023-01-30 11:27:37,025| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.automotive` has been localized to `en_US`.
D 2023-01-30 11:27:37,026| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.bank`.
D 2023-01-30 11:27:37,026| DEBUG    | [factory.py:factory:_find_provider_class:105] - Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
D 2023-01-30 11:27:37,027| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.barcode`.
D 2023-01-30 11:27:37,027| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.barcode` has been localized to `en_US`.
D 2023-01-30 11:27:37,029| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.color`.
D 2023-01-30 11:27:37,029| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.color` has been localized to `en_US`.
D 2023-01-30 11:27:37,030| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.company`.
D 2023-01-30 11:27:37,031| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.company` has been localized to `en_US`.
D 2023-01-30 11:27:37,031| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.credit_card`.
D 2023-01-30 11:27:37,032| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.credit_card` has been localized to `en_US`.
D 2023-01-30 11:27:37,032| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.currency`.
D 2023-01-30 11:27:37,033| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.currency` has been localized to `en_US`.
D 2023-01-30 11:27:37,034| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.date_time`.
D 2023-01-30 11:27:37,035| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.date_time` has been localized to `en_US`.
D 2023-01-30 11:27:37,035| DEBUG    | [factory.py:factory:_find_provider_class:125] - Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
D 2023-01-30 11:27:37,035| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.geo`.
D 2023-01-30 11:27:37,036| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.geo` has been localized to `en_US`.
D 2023-01-30 11:27:37,036| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.internet`.
D 2023-01-30 11:27:37,038| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.internet` has been localized to `en_US`.
D 2023-01-30 11:27:37,038| DEBUG    | [factory.py:factory:_find_provider_class:125] - Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
D 2023-01-30 11:27:37,038| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.job`.
D 2023-01-30 11:27:37,039| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.job` has been localized to `en_US`.
D 2023-01-30 11:27:37,040| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.lorem`.
D 2023-01-30 11:27:37,040| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.lorem` has been localized to `en_US`.
D 2023-01-30 11:27:37,042| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.misc`.
D 2023-01-30 11:27:37,042| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.misc` has been localized to `en_US`.
D 2023-01-30 11:27:37,042| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.person`.
D 2023-01-30 11:27:37,044| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.person` has been localized to `en_US`.
D 2023-01-30 11:27:37,048| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.phone_number`.
D 2023-01-30 11:27:37,050| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.phone_number` has been localized to `en_US`.
D 2023-01-30 11:27:37,051| DEBUG    | [factory.py:factory:_find_provider_class:125] - Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
D 2023-01-30 11:27:37,051| DEBUG    | [factory.py:factory:_find_provider_class:125] - Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
D 2023-01-30 11:27:37,051| DEBUG    | [factory.py:factory:_find_provider_class:95] - Looking for locale `en_US` in provider `faker.providers.ssn`.
D 2023-01-30 11:27:37,053| DEBUG    | [factory.py:factory:_find_provider_class:114] - Provider `faker.providers.ssn` has been localized to `en_US`.
D 2023-01-30 11:27:37,053| DEBUG    | [factory.py:factory:_find_provider_class:125] - Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
D 2023-01-30 11:27:37,061| DEBUG    | [connectionpool.py:connectionpool:_new_conn:971] - Starting new HTTPS connection (1): p10496-hk-bbs.ejoy.com:443
D 2023-01-30 11:27:37,165| DEBUG    | [connectionpool.py:connectionpool:_make_request:452] - https://p10496-hk-bbs.ejoy.com:443 "GET /api/bbs/S3G%E4%BA%8C%E5%91%A8%E5%B9%B4%E4%B8%A4%E8%A1%8C%E6%83%85%E4%B9%A6/index?count=100 HTTP/1.1" 200 None
D 2023-01-30 11:27:37,167| DEBUG    | [requeststart.py:requeststart:send_request:22] - 发起请求的参数为：{'url': 'https://p10496-hk-bbs.ejoy.com/api/bbs/S3G二周年两行情书/index?count=100', 'method': 'get'}
D 2023-01-30 11:27:37,170| DEBUG    | [asserts.py:asserts:assert_code:30] - Response_Code实际结果为：6088b66e2230325e4b1970e5120a11fc
D 2023-01-30 11:27:37,170| DEBUG    | [asserts.py:asserts:assert_code:31] - Response_Code预期结果为：3e4547b4bb12e9047950252d64b63472
E 2023-01-30 11:27:37,170| ERROR    | [asserts.py:asserts:assert_code:35] - 断言失败，Response_Code实际结果为：6088b66e2230325e4b1970e5120a11fc，Response预期结果为：3e4547b4bb12e9047950252d64b63472
E 2023-01-30 11:27:37,170| ERROR    | [asserts.py:asserts:assert_code:36] - 断言用例不通过！
