DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.address`.
DEBUG    faker.factory:factory.py:114 Provider `faker.providers.address` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.automotive`.
DEBUG    faker.factory:factory.py:114 Provider `faker.providers.automotive` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.bank`.
DEBUG    faker.factory:factory.py:105 Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.barcode`.
DEBUG    faker.factory:factory.py:114 Provider `faker.providers.barcode` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.color`.
DEBUG    faker.factory:factory.py:114 Provider `faker.providers.color` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.company`.
DEBUG    faker.factory:factory.py:114 Provider `faker.providers.company` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.credit_card`.
DEBUG    faker.factory:factory.py:114 Provider `faker.providers.credit_card` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.currency`.
DEBUG    faker.factory:factory.py:114 Provider `faker.providers.currency` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.date_time`.
DEBUG    faker.factory:factory.py:114 Provider `faker.providers.date_time` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:125 Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.geo`.
DEBUG    faker.factory:factory.py:114 Provider `faker.providers.geo` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.internet`.
DEBUG    faker.factory:factory.py:114 Provider `faker.providers.internet` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:125 Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.job`.
DEBUG    faker.factory:factory.py:114 Provider `faker.providers.job` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.lorem`.
DEBUG    faker.factory:factory.py:114 Provider `faker.providers.lorem` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.misc`.
DEBUG    faker.factory:factory.py:114 Provider `faker.providers.misc` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.person`.
DEBUG    faker.factory:factory.py:114 Provider `faker.providers.person` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.phone_number`.
DEBUG    faker.factory:factory.py:114 Provider `faker.providers.phone_number` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:125 Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:125 Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:95 Looking for locale `en_US` in provider `faker.providers.ssn`.
DEBUG    faker.factory:factory.py:114 Provider `faker.providers.ssn` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:125 Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): p10496-hk-bbs.ejoy.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:452 https://p10496-hk-bbs.ejoy.com:443 "GET /api/bbs/S3G%E4%BA%8C%E5%91%A8%E5%B9%B4%E4%B8%A4%E8%A1%8C%E6%83%85%E4%B9%A6/index?count=100 HTTP/1.1" 200 None
DEBUG    root:requeststart.py:22 发起请求的参数为：{'url': 'https://p10496-hk-bbs.ejoy.com/api/bbs/S3G二周年两行情书/index?count=100', 'method': 'get'}
DEBUG    root:asserts.py:30 Response_Code实际结果为：6ab256bb1feba80f9b3f7996328aa4a1
DEBUG    root:asserts.py:31 Response_Code预期结果为：3e4547b4bb12e9047950252d64b63472
ERROR    root:asserts.py:35 断言失败，Response_Code实际结果为：6ab256bb1feba80f9b3f7996328aa4a1，Response预期结果为：3e4547b4bb12e9047950252d64b63472
ERROR    root:asserts.py:36 断言用例不通过！